language: cpp
compiler:
  - gcc
before_script:
  - sudo apt-get install libboost-thread-dev libboost-system-dev libboost-filesystem-dev spring
  - cmake -DBUILD_TESTS=ON .
script:
  - make && make check
